
import { LineEdit } from "std-widgets.slint";

export component SearchInput inherits FocusScope {
  forward-focus: text_input;
  in-out property <string> text <=> text-input.text;

  callback search-changed(string);
  callback esc-pressed();

  KeyBinding {
    keys: @keys(Escape);
    activated => { root.esc-pressed(); }
  }

  text_input := LineEdit {
    width: parent.width;
    height: 40px;
    placeholder-text: "Search...";

    edited(value) => {
      root.search-changed(value)
    }
  }
}
