[package]
name = "feiri-ipc"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
feiri-core = { path = "../feiri-core" }
clap = { workspace = true, optional = true }
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures-core = "0.3.34"
tokio-stream.workspace = true

[features]
clap = ["dep:clap"]
