import { VerticalBox } from "std-widgets.slint";
import { SearchInput } from "widgets/search_input.slint";
import { SearchResultMenu } from "widgets/search_result_menu.slint";
import { MarkRowItem } from "./structs/mark_row_item.slint";

export component AppWindow inherits Window {
    in property <[MarkRowItem]> marks;

    width: 500px;
    no-frame: true;
    callback search-requested <=> search.search-changed;

    forward-focus: search;

    window-scope := FocusScope {
      VerticalBox {
        padding: 5px;
          search := SearchInput {
            esc-pressed => {
              results.focus();
            }
          }

        results := SearchResultMenu {
          insert-pressed => {
            search.focus();
          }
          height: min(root.marks.length * 36px, 300px);
          marks: root.marks;
        }
      }
    }
}
