import { VerticalBox } from "std-widgets.slint";
import { SearchInput } from "widgets/search_input.slint";
import { SearchResultMenu } from "widgets/search_result_menu.slint";
import { MarkRowItem } from "./structs/mark_row_item.slint";

export component AppWindow inherits Window {
    in property <[MarkRowItem]> marks;
    in property <string> app-font-family;
    in property <length> app-font-size;
    callback search-requested <=> search.search-changed;
    callback focus-requested <=> results.return-pressed;
    callback delete-requested <=> results.delete-pressed;

    forward-focus: results;

    default-font-family: app-font-family;
    default-font-size: app-font-size;

    no-frame: true;
    background: transparent;
    width: 500px;

    Rectangle {
      width: 100%;
      height: 100%;
      // background: #ff0000;
      clip: true;
      // border-radius: 16px;
      window-scope := FocusScope {
        VerticalBox {
          padding: 5px;
            search := SearchInput {
              esc-pressed => {
                results.focus();
              }
            }

          results := SearchResultMenu {
            insert-pressed => {
              search.focus();
            }
            height: min(root.marks.length * 36px, 300px);
            marks: root.marks;
          }
        }
      }
    }
}
