name: feiri crates CI

on:
  pull_request:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "flake.nix"
      - ".github/workflows/feiri-ci.yml"
  push:
    branches: [ main ]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "flake.nix"
      - ".github/workflows/feiri-ci.yml"
  workflow_dispatch:

jobs:
  nix-build-daemon-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build niqol Nix package
        run: nix build .#daemon

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check formatting
        run : nix develop -c cargo fmt --check

      - name: Clippy
        run: nix develop -c cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Test
        run: nix develop -c cargo test
