name: Nix checks

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Platform checks
        run: nix flake check --print-build-logs
